#!/bin/bash


# Control OCI images
# Iván Chavero <ichavero@chavero.com.mx>
# TODO: stop using docker

#TODO use getops
COMMAND="$1"
OCI_IMAGE_NAME="$2"
RUNC="/usr/bin/runc"
OCI_IMAGE_BASE="/home/vservers/OCI-Image-Bundles"
OCI_IMAGE_DIR="${OCI_IMAGE_BASE}/${OCI_IMAGE_NAME}"




# Generate image from a docker container
function generate_bundle {
	#TODO
	if [ -d "${OCI_IMAGE_DIR}" ]; then
		echo "$OCI_IMAGE_DIR directory already exists! aborting..."
		exit
	fi
	mkdir -p $OCI_IMAGE_DIR/rootfs
	cd $OCI_IMAGE_DIR
	podman export $(podman create $OCI_IMAGE_NAME) | tar -C rootfs -xvf -
	cp templates/config-template.json $OCI_IMAGE_DIR/rootfs/.
	echo "Done"
}

# Delete OCI image bundle
function delete_bundle {
	if [ ! -d "${OCI_IMAGE_DIR}" ]; then
		echo "$OCI_IMAGE_DIR directory does not exist! aborting..."
		exit
	fi
	echo "Deleting $OCI_IMAGE_DIR"
	rm -rf $OCI_IMAGE_DIR
	echo "Done"
}


case "$COMMAND" in 
	generate)
		echo "Generating OCI image bundle ${OCI_IMAGE_NAME}"
		generate_bundle ${OCI_IMAGE_NAME}
		;;
	delete)
		echo "Deleting OCI image bundle ${OCI_IMAGE_NAME}"
		delete_bundle ${OCI_IMAGE_NAME}
		;;
	*)
		echo "Usage: $0 generate|delete OCI_IMAGE_NAME"
		exit
esac



