FROM quay.io/centos/centos:stream9

ENV SOTOLITO_CENTOS_VPS_VERSION=9.0.0\
    SUMMARY="SotolitoLabs Centos 9 VPS" \
    DESCRIPTION="Centos 9 Image for SotlitoVPS"

LABEL summary="$SUMMARY" \
      description="$DESCRIPTION" \
      io.k8s.description="$DESCRIPTION" \
      io.k8s.display-name="SotolitoOS centos 9" \
      name="sotolito/centos-vps" \
      version="9.0.0" \
      usage="vpsctl start vps_name" \
      maintainer="Iván Chavero <ichavero@chavero.com.mx>"

RUN set -eux                                      && \
    echo "nameserver 8.8.8.8" > /etc/resolv.conf  && \
    dnf groupinstall --allowerasing -y core       && \
    dnf install -y openssh-server openssh-clients && \
    dnf clean all

